GET http://127.0.0.1:5000/users/
Accept: application/json

###
POST http://127.0.0.1:5000/users/
Content-Type: application/json

{
  "user_name": "john",
  "password": "test",
  "role": "admin"
}

###
GET http://127.0.0.1:5000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtpcmlsbCIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTY4OTMzNjcxNX0.cGjT5xa635lD3nRYLBlJwiFVbQV9xMndV2AILewZsHs